<?php
if (!defined('_GNUBOARD_')) exit;
$data=array (
  0 => 
  array (
    'text' => '출근부',
    'href' => '#',
    'icon' => 'fa-calendar',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '오피-강남영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=opiGangnam_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opiGangnam_at',
        'bo_table' => 'opiGangnam_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      1 => 
      array (
        'text' => '오피-비강남',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=opiBigangnam_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opiBigangnam_at',
        'bo_table' => 'opiBigangnam_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      2 => 
      array (
        'text' => '오피-경기영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=opiGyeonggi_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opiGyeonggi_at',
        'bo_table' => 'opiGyeonggi_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      3 => 
      array (
        'text' => '오피-인천/부천',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=opiInchon_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opiInchon_at',
        'bo_table' => 'opiInchon_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      4 => 
      array (
        'text' => '오피-강원/충청/대전',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=opiDaejeon',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opiDaejeon',
        'bo_table' => 'opiDaejeon',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      5 => 
      array (
        'text' => '오피-경상영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=opiGyeongsang_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opiGyeongsang_at',
        'bo_table' => 'opiGyeongsang_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      6 => 
      array (
        'text' => '오피-대구영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=opiDaegu_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opiDaegu_at',
        'bo_table' => 'opiDaegu_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      7 => 
      array (
        'text' => '오피-전라/제주',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=opiJeju_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opiJeju_at',
        'bo_table' => 'opiJeju_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      8 => 
      array (
        'text' => '안마-서울영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=anmaSeoul_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-anmaSeoul_at',
        'bo_table' => 'anmaSeoul_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      9 => 
      array (
        'text' => '안마-지방영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=anmaChiban_at',
        'icon' => 'fa-wpforms',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-anmaChiban_at',
        'bo_table' => 'anmaChiban_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      10 => 
      array (
        'text' => '건마-서울영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=gonma_seoul',
        'icon' => 'fa-wpforms',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gonma_seoul',
        'bo_table' => 'gonma_seoul',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      11 => 
      array (
        'text' => '건마-경기영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=gonmaKyonggi_at',
        'icon' => 'fa-wpforms',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gonmaKyonggi_at',
        'bo_table' => 'gonmaKyonggi_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      12 => 
      array (
        'text' => '건마-인천/부천',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=gonmaInchonBuchon_at',
        'icon' => 'fa-wpforms',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gonmaInchonBuchon_at',
        'bo_table' => 'gonmaInchonBuchon_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      13 => 
      array (
        'text' => '건마-강원/충천/대전',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=gunmaTechon_at',
        'icon' => 'fa-wpforms',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gunmaTechon_at',
        'bo_table' => 'gunmaTechon_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      14 => 
      array (
        'text' => '건마-경상/전라/제주',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=gonmaJeju_at',
        'icon' => 'fa-wpforms',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gonmaJeju_at',
        'bo_table' => 'gonmaJeju_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      15 => 
      array (
        'text' => '술집-서울영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=suljibSeoul_at',
        'icon' => 'fa-wpforms',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-suljibSeoul_at',
        'bo_table' => 'suljibSeoul_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      16 => 
      array (
        'text' => '술집-지방영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=suljibChiban_at',
        'icon' => 'fa-wpforms',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-suljibChiban_at',
        'bo_table' => 'suljibChiban_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      17 => 
      array (
        'text' => '휴게텔-서울영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=hyugetelSeoul_at',
        'icon' => 'fa-wpforms',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugetelSeoul_at',
        'bo_table' => 'hyugetelSeoul_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      18 => 
      array (
        'text' => '휴게텔-경기영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=hyugetelKyonggi_at',
        'icon' => 'fa-wpforms',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugetelKyonggi_at',
        'bo_table' => 'hyugetelKyonggi_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      19 => 
      array (
        'text' => '휴게텔-인천/부천',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=hyugetelInchon_at',
        'icon' => 'fa-wpforms',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugetelInchon_at',
        'bo_table' => 'hyugetelInchon_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      20 => 
      array (
        'text' => '휴게텔 강원/충청/대전',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=hyugetelDaejeon_at',
        'icon' => 'fa-wpforms',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugetelDaejeon_at',
        'bo_table' => 'hyugetelDaejeon_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      21 => 
      array (
        'text' => '휴게텔 경상/전라/제주',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=hyugetelJeju_at',
        'icon' => 'fa-wpforms',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugetelJeju_at',
        'bo_table' => 'hyugetelJeju_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      22 => 
      array (
        'text' => '키스방-전국영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=kissAll',
        'icon' => 'fa-wpforms',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-kissAll',
        'bo_table' => 'kissAll',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      23 => 
      array (
        'text' => '립카페-전국영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=lipcafeAll_at',
        'icon' => 'fa-wpforms',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-lipcafeAll_at',
        'bo_table' => 'lipcafeAll_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      24 => 
      array (
        'text' => '핸플/패티쉬영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=show_at',
        'icon' => 'fa-wpforms',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-show_at',
        'bo_table' => 'show_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      25 => 
      array (
        'text' => '선불폰/프로필 여행사/기타',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=trip_at',
        'icon' => 'fa-wpforms',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-trip_at',
        'bo_table' => 'trip_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
    ),
  ),
  1 => 
  array (
    'text' => '후기',
    'href' => '#',
    'icon' => 'fa-commenting-o',
    'target' => '_self',
    'line' => '공지사항',
    'sp' => '1',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '오피-강남영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=opiGangnam_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opiGangnam_re',
        'bo_table' => 'opiGangnam_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      1 => 
      array (
        'text' => '오피-비강남',
        'href' => '/bbs/board.php?bo_table=opiBigangnam',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      2 => 
      array (
        'text' => '오피-경기영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=opiGyeonggi_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opiGyeonggi_re',
        'bo_table' => 'opiGyeonggi_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      3 => 
      array (
        'text' => '오피-인천/부천',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=opiInchon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opiInchon_re',
        'bo_table' => 'opiInchon_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      4 => 
      array (
        'text' => '오피-강원/충청/대전',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=opiDaejeon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opiDaejeon_re',
        'bo_table' => 'opiDaejeon_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      5 => 
      array (
        'text' => '오피-경상영토 ',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=opiGyeongsang_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opiGyeongsang_re',
        'bo_table' => 'opiGyeongsang_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      6 => 
      array (
        'text' => '오피-대구영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=opiDaegu_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opiDaegu_re',
        'bo_table' => 'opiDaegu_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      7 => 
      array (
        'text' => '오피-전라/제주',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=opiJeju_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opiJeju_re',
        'bo_table' => 'opiJeju_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      8 => 
      array (
        'text' => '안마-서울영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=anmaSeoul_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-anmaSeoul_re',
        'bo_table' => 'anmaSeoul_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      9 => 
      array (
        'text' => '안마-지방영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=anmaChiban_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-anmaChiban_re',
        'bo_table' => 'anmaChiban_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      10 => 
      array (
        'text' => '건마-서울영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=gonmaSeoul_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gonmaSeoul_re',
        'bo_table' => 'gonmaSeoul_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      11 => 
      array (
        'text' => '건마-경기영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=gonmaKyonggi_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gonmaKyonggi_re',
        'bo_table' => 'gonmaKyonggi_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      12 => 
      array (
        'text' => '건마-인천/부천',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=gonmaInchonBuchon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gonmaInchonBuchon_re',
        'bo_table' => 'gonmaInchonBuchon_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      13 => 
      array (
        'text' => '건마 (강원/충청/대전)',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=gunmaTechon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gunmaTechon_re',
        'bo_table' => 'gunmaTechon_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      14 => 
      array (
        'text' => '건마 경상/전라/제주',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=gonmaJeju_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gonmaJeju_re',
        'bo_table' => 'gonmaJeju_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      15 => 
      array (
        'text' => '술집-서울영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=suljibSeoul_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-suljibSeoul_re',
        'bo_table' => 'suljibSeoul_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      16 => 
      array (
        'text' => '술집-지방영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=suljibChiban_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-suljibChiban_re',
        'bo_table' => 'suljibChiban_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      17 => 
      array (
        'text' => '휴게텔-서울영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=hyugetelSeoul_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugetelSeoul_re',
        'bo_table' => 'hyugetelSeoul_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      18 => 
      array (
        'text' => '휴게텔-경기영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=hyugetelKyonggi_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugetelKyonggi_re',
        'bo_table' => 'hyugetelKyonggi_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      19 => 
      array (
        'text' => '휴게텔-인천/부천',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=hyugetelInchon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugetelInchon_re',
        'bo_table' => 'hyugetelInchon_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      20 => 
      array (
        'text' => '휴게텔 강원/충청/대전',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=hyugetelDaejeon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugetelDaejeon_re',
        'bo_table' => 'hyugetelDaejeon_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      21 => 
      array (
        'text' => '휴게텔 경상/전라/제주',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=hyugetelJeju_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugetelJeju_re',
        'bo_table' => 'hyugetelJeju_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      22 => 
      array (
        'text' => '키스방-전국영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=kissAll_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-kissAll_re',
        'bo_table' => 'kissAll_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      23 => 
      array (
        'text' => '립카페-전국영토',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=lipcafeAll_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-lipcafeAll_re',
        'bo_table' => 'lipcafeAll_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      24 => 
      array (
        'text' => '핸플/패티쉬영토',
        'href' => '#',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      25 => 
      array (
        'text' => '선불폰/프로필 여행사/기타',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=trip_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-trip_re',
        'bo_table' => 'trip_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
    ),
  ),
  2 => 
  array (
    'text' => '커뮤니티',
    'href' => '#',
    'icon' => 'fa-comments',
    'target' => '_self',
    'line' => '공지사항',
    'sp' => '1',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '출석체크',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=attendance',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '공지사항',
        'sp' => '1',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-attendance',
        'bo_table' => 'attendance',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      1 => 
      array (
        'text' => '공지사항',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=notice',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-notice',
        'bo_table' => 'notice',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      2 => 
      array (
        'text' => '가입 인사',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=Greeting',
        'icon' => 'fa-comments',
        'target' => '_top',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-Greeting',
        'bo_table' => 'Greeting',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      3 => 
      array (
        'text' => '자유 게시판',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=free',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-free',
        'bo_table' => 'free',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      4 => 
      array (
        'text' => ' 미수다(女)',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=woman',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-woman',
        'bo_table' => 'woman',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      5 => 
      array (
        'text' => ' 이벤트',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=event',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-event',
        'bo_table' => 'event',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      6 => 
      array (
        'text' => '쿠폰구매',
        'href' => '#',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      7 => 
      array (
        'text' => '정모 게시판',
        'href' => '#',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      8 => 
      array (
        'text' => '외성 게시판',
        'href' => '#',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      9 => 
      array (
        'text' => '왕궁 게시판',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=Palace',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-Palace',
        'bo_table' => 'Palace',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      10 => 
      array (
        'text' => '아이템샵',
        'href' => '#',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      11 => 
      array (
        'text' => '건의사항',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=Suggestions',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-Suggestions',
        'bo_table' => 'Suggestions',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      12 => 
      array (
        'text' => '트위터 인증',
        'href' => '#',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  3 => 
  array (
    'text' => '고객센터',
    'href' => '#',
    'icon' => 'fa-headphones',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '1:1문의',
        'href' => 'http://localhost/gnuboard/bbs/qalist.php',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-qa',
      ),
      1 => 
      array (
        'text' => '파운드페니로전환',
        'href' => '#',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      2 => 
      array (
        'text' => '페니구매',
        'href' => '#',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      3 => 
      array (
        'text' => '환전',
        'href' => '#',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      4 => 
      array (
        'text' => '장터게시판',
        'href' => '#',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      5 => 
      array (
        'text' => '구인구직 게시판',
        'href' => '#',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      6 => 
      array (
        'text' => '실장업무게시판',
        'href' => '#',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  4 => 
  array (
    'text' => '명예의전당',
    'href' => '#',
    'icon' => 'fa-trophy',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '계급 랭킹',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=bestmember',
        'icon' => 'fa-trophy',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-bestmember',
        'bo_table' => 'bestmember',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      1 => 
      array (
        'text' => '파운드 랭킹',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=pointrank',
        'icon' => 'fa-trophy',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-pointrank',
        'bo_table' => 'pointrank',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      2 => 
      array (
        'text' => '외성 랭킹',
        'href' => '#',
        'icon' => 'fa-trophy',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  5 => 
  array (
    'text' => '파운드 게임',
    'href' => '#',
    'icon' => 'fa-globe',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
  ),
  6 => 
  array (
    'text' => ' 페니 게임',
    'href' => '#',
    'icon' => 'fa-bullseye',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '포카',
        'href' => '#',
        'icon' => 'fa-bullseye',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      1 => 
      array (
        'text' => '바둑이',
        'href' => '#',
        'icon' => 'fa-bullseye',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      2 => 
      array (
        'text' => '맞고',
        'href' => '#',
        'icon' => 'fa-bullseye',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  7 => 
  array (
    'text' => ' 자료실',
    'href' => '#',
    'icon' => 'fa-play-circle',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '  영화 ',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=movie',
        'icon' => 'fa-play-circle',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-movie',
        'bo_table' => 'movie',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      1 => 
      array (
        'text' => 'TV영상',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=tv',
        'icon' => 'fa-play-circle',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-tv',
        'bo_table' => 'tv',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      2 => 
      array (
        'text' => ' 웹툰/야설 ',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=ucc',
        'icon' => 'fa-play-circle',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-ucc',
        'bo_table' => 'ucc',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      3 => 
      array (
        'text' => '유튜브 영상',
        'href' => 'http://localhost/gnuboard/bbs/board.php?bo_table=request',
        'icon' => 'fa-play-circle',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-request',
        'bo_table' => 'request',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
    ),
  ),
);
?>