<?php
if (!defined('_GNUBOARD_')) exit;
$data=array (
  0 => 
  array (
    'text' => '출근부',
    'href' => '#',
    'icon' => 'fa-calendar',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '오피-강남영토',
        'href' => '/bbs/board.php?bo_table=opigangnam_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      1 => 
      array (
        'text' => '오피-비강남',
        'href' => '/bbs/board.php?bo_table=opibigangnam_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      2 => 
      array (
        'text' => '오피-경기영토',
        'href' => '/bbs/board.php?bo_table=opigyeonggi_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      3 => 
      array (
        'text' => '오피-인천/부천',
        'href' => '/bbs/board.php?bo_table=opiinchon_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      4 => 
      array (
        'text' => '오피-강원/충청/대전',
        'href' => '/bbs/board.php?bo_table=opidaejeon_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      5 => 
      array (
        'text' => '오피-경상영토',
        'href' => '/bbs/board.php?bo_table=opigyeongsang_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      6 => 
      array (
        'text' => '오피-대구영토',
        'href' => '/bbs/board.php?bo_table=opidaegu_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      7 => 
      array (
        'text' => '오피-전라/제주',
        'href' => '/bbs/board.php?bo_table=opijeju_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      8 => 
      array (
        'text' => '휴게텔-서울영토',
        'href' => '/bbs/board.php?bo_table=hyugetelseoul_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      9 => 
      array (
        'text' => '휴게텔-경기영토',
        'href' => '/bbs/board.php?bo_table=hyugetelkyonggi_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      10 => 
      array (
        'text' => '휴게텔-인천/부천',
        'href' => '/bbs/board.php?bo_table=hyugetelinchon_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      11 => 
      array (
        'text' => '휴게텔-강원/충청/대전',
        'href' => '/bbs/board.php?bo_table=hyugeteldaejeon_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      12 => 
      array (
        'text' => '휴게텔-경상/전라/제주',
        'href' => '/bbs/board.php?bo_table=hyugeteljeju_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      13 => 
      array (
        'text' => '건마-서울영토',
        'href' => '/bbs/board.php?bo_table=gonmaseoul_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      14 => 
      array (
        'text' => '건마-경기영토',
        'href' => '/bbs/board.php?bo_table=gonmakyonggi_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      15 => 
      array (
        'text' => '건마-인천/부천',
        'href' => '/bbs/board.php?bo_table=gonmainchonbuchon_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      16 => 
      array (
        'text' => '건마-강원/충천/대전',
        'href' => '/bbs/board.php?bo_table=gunmatechon_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      17 => 
      array (
        'text' => '건마-경상/전라/제주',
        'href' => '/bbs/board.php?bo_table=gonmajeju_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      18 => 
      array (
        'text' => '술집-서울영토',
        'href' => '/bbs/board.php?bo_table=suljibseoul_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      19 => 
      array (
        'text' => '술집-지방영토',
        'href' => '/bbs/board.php?bo_table=suljibchiban_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      20 => 
      array (
        'text' => '안마-서울영토',
        'href' => '/bbs/board.php?bo_table=anmaseoul_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      21 => 
      array (
        'text' => '안마-지방영토',
        'href' => '/bbs/board.php?bo_table=anmachiban_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      22 => 
      array (
        'text' => '출장-전국영토',
        'href' => '/bbs/board.php?bo_table=chuljanall_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      23 => 
      array (
        'text' => '키스방-전국영토',
        'href' => '/bbs/board.php?bo_table=kissall_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      24 => 
      array (
        'text' => '립카페-전국영토',
        'href' => '/bbs/board.php?bo_table=lipcafeall_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      25 => 
      array (
        'text' => '핸플/패티쉬영토',
        'href' => '/bbs/board.php?bo_table=show_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      26 => 
      array (
        'text' => '선불폰/프로필 여행사/기타',
        'href' => '/bbs/board.php?bo_table=other_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  1 => 
  array (
    'text' => '후기',
    'href' => '#',
    'icon' => 'fa-commenting-o',
    'target' => '_self',
    'line' => '공지사항',
    'sp' => '1',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '오피-강남영토',
        'href' => '/bbs/board.php?bo_table=opigangnam_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '오피',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      1 => 
      array (
        'text' => '오피-비강남',
        'href' => '/bbs/board.php?bo_table=opibigangnam_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      2 => 
      array (
        'text' => '오피-경기영토',
        'href' => '/bbs/board.php?bo_table=opigyeonggi_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      3 => 
      array (
        'text' => '오피-인천/부천',
        'href' => '/bbs/board.php?bo_table=opiinchon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      4 => 
      array (
        'text' => '오피-강원/충청/대전',
        'href' => '/bbs/board.php?bo_table=opidaejeon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      5 => 
      array (
        'text' => '오피-경상영토 ',
        'href' => '/bbs/board.php?bo_table=opigyeongsang_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      6 => 
      array (
        'text' => '오피-대구영토',
        'href' => '/bbs/board.php?bo_table=opidaegu_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      7 => 
      array (
        'text' => '오피-전라/제주',
        'href' => '/bbs/board.php?bo_table=opijeju_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      8 => 
      array (
        'text' => '휴게텔-서울영토',
        'href' => '/bbs/board.php?bo_table=hyugetelseoul_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      9 => 
      array (
        'text' => '휴게텔-경기영토',
        'href' => '/bbs/board.php?bo_table=hyugetelkyonggi_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      10 => 
      array (
        'text' => '휴게텔-인천/부천',
        'href' => '/bbs/board.php?bo_table=hyugetelinchon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      11 => 
      array (
        'text' => '휴게텔 강원/충청/대전',
        'href' => '/bbs/board.php?bo_table=hyugeteldaejeon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      12 => 
      array (
        'text' => '휴게텔 경상/전라/제주',
        'href' => '/bbs/board.php?bo_table=hyugeteljeju_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      13 => 
      array (
        'text' => '건마-서울영토',
        'href' => '/bbs/board.php?bo_table=gonmaseoul_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      14 => 
      array (
        'text' => '건마-경기영토',
        'href' => '/bbs/board.php?bo_table=gonmakyonggi_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      15 => 
      array (
        'text' => '건마-인천/부천',
        'href' => '/bbs/board.php?bo_table=gonmainchonbuchon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      16 => 
      array (
        'text' => '건마-강원/충청/대전',
        'href' => '/bbs/board.php?bo_table=gunmatechon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      17 => 
      array (
        'text' => '건마-경상/전라/제주',
        'href' => '/bbs/board.php?bo_table=gonmajeju_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      18 => 
      array (
        'text' => '술집-서울영토',
        'href' => '/bbs/board.php?bo_table=suljibseoul_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      19 => 
      array (
        'text' => '술집-지방영토',
        'href' => '/bbs/board.php?bo_table=suljibchiban_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      20 => 
      array (
        'text' => '안마-서울영토',
        'href' => '/bbs/board.php?bo_table=anmaseoul_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      21 => 
      array (
        'text' => '안마-지방영토',
        'href' => '/bbs/board.php?bo_table=anmachiban_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      22 => 
      array (
        'text' => '출장-전국영토',
        'href' => '/bbs/board.php?bo_table=chuljanall_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      23 => 
      array (
        'text' => '키스방-전국영토',
        'href' => '/bbs/board.php?bo_table=kissall_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      24 => 
      array (
        'text' => '립카페-전국영토',
        'href' => '/bbs/board.php?bo_table=lipcafeall_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      25 => 
      array (
        'text' => '핸플/패티쉬영토',
        'href' => '/bbs/board.php?bo_table=show_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      26 => 
      array (
        'text' => '선불폰/프로필 여행사/기타',
        'href' => '/bbs/board.php?bo_table=other_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  2 => 
  array (
    'text' => '커뮤니티',
    'href' => '#',
    'icon' => 'fa-comments',
    'target' => '_self',
    'line' => '공지사항',
    'sp' => '1',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '출석체크',
        'href' => '/plugin/attendance/attendance.php',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '공지사항',
        'sp' => '1',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      1 => 
      array (
        'text' => '공지사항',
        'href' => '/bbs/board.php?bo_table=notice',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      2 => 
      array (
        'text' => '가입 인사',
        'href' => '/bbs/board.php?bo_table=greeting',
        'icon' => 'fa-comments',
        'target' => '_top',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      3 => 
      array (
        'text' => '자유 게시판',
        'href' => '/bbs/board.php?bo_table=free',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      4 => 
      array (
        'text' => '미수다(女)',
        'href' => '/bbs/board.php?bo_table=woman',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      5 => 
      array (
        'text' => '이벤트',
        'href' => '/bbs/board.php?bo_table=event',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      6 => 
      array (
        'text' => '가문게시판',
        'href' => '/bbs/blank3.php',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      7 => 
      array (
        'text' => '왕궁 게시판',
        'href' => '/bbs/blank2.php',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      8 => 
      array (
        'text' => '아이템샵',
        'href' => '/bbs/blank7.php',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      9 => 
      array (
        'text' => '건의사항',
        'href' => '/bbs/board.php?bo_table=suggestions',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      10 => 
      array (
        'text' => '트위터 인증',
        'href' => '/bbs/board.php?bo_table=twitter',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  3 => 
  array (
    'text' => '고객센터',
    'href' => 'bbs/blank.php',
    'icon' => 'fa-headphones',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '1:1문의',
        'href' => '/bbs/qalist.php',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      1 => 
      array (
        'text' => '환전',
        'href' => '/bbs/blank3.php',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      2 => 
      array (
        'text' => '구인구직 게시판',
        'href' => '/bbs/board.php?bo_table=job',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      3 => 
      array (
        'text' => '실장업무게시판',
        'href' => '/bbs/board.php?bo_table=work_board',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  4 => 
  array (
    'text' => '명예의전당',
    'href' => '/bbs/blank6.php',
    'icon' => 'fa-trophy',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '계급 랭킹',
        'href' => '/bbs/board.php?bo_table=levelrank',
        'icon' => 'fa-trophy',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      1 => 
      array (
        'text' => '파운드 랭킹',
        'href' => '/bbs/board.php?bo_table=pointrank',
        'icon' => 'fa-trophy',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      2 => 
      array (
        'text' => '가문 랭킹',
        'href' => '/bbs/blank6.php',
        'icon' => 'fa-trophy',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  5 => 
  array (
    'text' => '파운드 게임',
    'href' => '/bbs/blank5.php',
    'icon' => 'fa-bullseye',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '파워볼',
        'href' => '/bbs/blank2.php',
        'icon' => 'fa-bullseye',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      1 => 
      array (
        'text' => '홀덤',
        'href' => '/bbs/blank5.php',
        'icon' => 'fa-bullseye',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      2 => 
      array (
        'text' => '바둑이',
        'href' => '/bbs/blank4.php',
        'icon' => 'fa-bullseye',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      3 => 
      array (
        'text' => '맞고',
        'href' => '/bbs/blank5.php',
        'icon' => 'fa-bullseye',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      4 => 
      array (
        'text' => '포카',
        'href' => '/bbs/blank1.php',
        'icon' => 'fa-bullseye',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  6 => 
  array (
    'text' => ' 자료실',
    'href' => '#',
    'icon' => 'fa-play-circle',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '영화 ',
        'href' => '/bbs/board.php?bo_table=movie',
        'icon' => 'fa-play-circle',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      1 => 
      array (
        'text' => 'TV영상',
        'href' => '/bbs/board.php?bo_table=tv',
        'icon' => 'fa-play-circle',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      2 => 
      array (
        'text' => '웹툰/야설 ',
        'href' => '/bbs/board.php?bo_table=ucc',
        'icon' => 'fa-play-circle',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      3 => 
      array (
        'text' => '유튜브 영상',
        'href' => '/bbs/board.php?bo_table=request',
        'icon' => 'fa-play-circle',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
);
?>