<?php
if (!defined('_GNUBOARD_')) exit;
$data=array (
  0 => 
  array (
    'text' => '출근부',
    'href' => '#',
    'icon' => 'fa-calendar',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '오피-강남영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=opigangnam_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opigangnam_at',
        'bo_table' => 'opigangnam_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      1 => 
      array (
        'text' => '오피-비강남',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=opibigangnam_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opibigangnam_at',
        'bo_table' => 'opibigangnam_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      2 => 
      array (
        'text' => '오피-경기영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=opigyeonggi_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opigyeonggi_at',
        'bo_table' => 'opigyeonggi_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      3 => 
      array (
        'text' => '오피-인천/부천',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=opiinchon_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opiinchon_at',
        'bo_table' => 'opiinchon_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      4 => 
      array (
        'text' => '오피-강원/충청/대전',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=opidaejeon_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opidaejeon_at',
        'bo_table' => 'opidaejeon_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      5 => 
      array (
        'text' => '오피-경상영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=opigyeongsang_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opigyeongsang_at',
        'bo_table' => 'opigyeongsang_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      6 => 
      array (
        'text' => '오피-대구영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=opidaegu_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opidaegu_at',
        'bo_table' => 'opidaegu_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      7 => 
      array (
        'text' => '오피-전라/제주',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=opijeju_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opijeju_at',
        'bo_table' => 'opijeju_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      8 => 
      array (
        'text' => '안마-서울영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=anmaseoul_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-anmaseoul_at',
        'bo_table' => 'anmaseoul_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      9 => 
      array (
        'text' => '안마-지방영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=anmachiban_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-anmachiban_at',
        'bo_table' => 'anmachiban_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      10 => 
      array (
        'text' => '건마-서울영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=gonmaseoul_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gonmaseoul_at',
        'bo_table' => 'gonmaseoul_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      11 => 
      array (
        'text' => '건마-경기영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=gonmakyonggi_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gonmakyonggi_at',
        'bo_table' => 'gonmakyonggi_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      12 => 
      array (
        'text' => '건마-인천/부천',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=gonmainchonbuchon_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gonmainchonbuchon_at',
        'bo_table' => 'gonmainchonbuchon_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      13 => 
      array (
        'text' => '건마-강원/충천/대전',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=gunmatechon_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gunmatechon_at',
        'bo_table' => 'gunmatechon_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      14 => 
      array (
        'text' => '건마-경상/전라/제주',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=gonmajeju_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gonmajeju_at',
        'bo_table' => 'gonmajeju_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      15 => 
      array (
        'text' => '술집-서울영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=suljibseoul_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-suljibseoul_at',
        'bo_table' => 'suljibseoul_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      16 => 
      array (
        'text' => '술집-지방영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=suljibchiban_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-suljibchiban_at',
        'bo_table' => 'suljibchiban_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      17 => 
      array (
        'text' => '휴게텔-서울영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=hyugetelseoul_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugetelseoul_at',
        'bo_table' => 'hyugetelseoul_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      18 => 
      array (
        'text' => '휴게텔-경기영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=hyugetelkyonggi_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugetelkyonggi_at',
        'bo_table' => 'hyugetelkyonggi_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      19 => 
      array (
        'text' => '휴게텔-인천/부천',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=hyugetelinchon_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugetelinchon_at',
        'bo_table' => 'hyugetelinchon_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      20 => 
      array (
        'text' => '휴게텔 강원/충청/대전',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=hyugeteldaejeon_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugeteldaejeon_at',
        'bo_table' => 'hyugeteldaejeon_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      21 => 
      array (
        'text' => '휴게텔 경상/전라/제주',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=hyugeteljeju_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugeteljeju_at',
        'bo_table' => 'hyugeteljeju_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      22 => 
      array (
        'text' => '키스방-전국영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=kissall_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-kissall_at',
        'bo_table' => 'kissall_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      23 => 
      array (
        'text' => '립카페-전국영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=lipcafeall_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-lipcafeall_at',
        'bo_table' => 'lipcafeall_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      24 => 
      array (
        'text' => '핸플/패티쉬영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=show_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-show_at',
        'bo_table' => 'show_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      25 => 
      array (
        'text' => '선불폰/프로필 여행사/기타',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=trip_at',
        'icon' => 'fa-calendar',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-trip_at',
        'bo_table' => 'trip_at',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
    ),
  ),
  1 => 
  array (
    'text' => '후기',
    'href' => '#',
    'icon' => 'fa-commenting-o',
    'target' => '_self',
    'line' => '공지사항',
    'sp' => '1',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '오피-강남영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=opigangnam_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opigangnam_re',
        'bo_table' => 'opigangnam_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      1 => 
      array (
        'text' => '오피-비강남',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=opibigangnam_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opibigangnam_re',
        'bo_table' => 'opibigangnam_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      2 => 
      array (
        'text' => '오피-경기영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=opigyeonggi_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opigyeonggi_re',
        'bo_table' => 'opigyeonggi_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      3 => 
      array (
        'text' => '오피-인천/부천',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=opiinchon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opiinchon_re',
        'bo_table' => 'opiinchon_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      4 => 
      array (
        'text' => '오피-강원/충청/대전',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=opidaejeon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opidaejeon_re',
        'bo_table' => 'opidaejeon_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      5 => 
      array (
        'text' => '오피-경상영토 ',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=opigyeongsang_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opigyeongsang_re',
        'bo_table' => 'opigyeongsang_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      6 => 
      array (
        'text' => '오피-대구영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=opidaegu_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opidaegu_re',
        'bo_table' => 'opidaegu_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      7 => 
      array (
        'text' => '오피-전라/제주',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=opijeju_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-opijeju_re',
        'bo_table' => 'opijeju_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      8 => 
      array (
        'text' => '안마-서울영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=anmaseoul_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-anmaseoul_re',
        'bo_table' => 'anmaseoul_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      9 => 
      array (
        'text' => '안마-지방영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=anmachiban_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-anmachiban_re',
        'bo_table' => 'anmachiban_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      10 => 
      array (
        'text' => '건마-서울영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=gonmaseoul_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gonmaseoul_re',
        'bo_table' => 'gonmaseoul_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      11 => 
      array (
        'text' => '건마-경기영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=gonmakyonggi_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gonmakyonggi_re',
        'bo_table' => 'gonmakyonggi_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      12 => 
      array (
        'text' => '건마-인천/부천',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=gonmainchonbuchon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gonmainchonbuchon_re',
        'bo_table' => 'gonmainchonbuchon_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      13 => 
      array (
        'text' => '건마 (강원/충청/대전)',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=gunmatechon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gunmatechon_re',
        'bo_table' => 'gunmatechon_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      14 => 
      array (
        'text' => '건마 경상/전라/제주',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=gonmajeju_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-gonmajeju_re',
        'bo_table' => 'gonmajeju_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      15 => 
      array (
        'text' => '술집-서울영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=suljibseoul_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-suljibseoul_re',
        'bo_table' => 'suljibseoul_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      16 => 
      array (
        'text' => '술집-지방영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=suljibchiban_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-suljibchiban_re',
        'bo_table' => 'suljibchiban_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      17 => 
      array (
        'text' => '휴게텔-서울영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=hyugetelseoul_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugetelseoul_re',
        'bo_table' => 'hyugetelseoul_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      18 => 
      array (
        'text' => '휴게텔-경기영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=hyugetelkyonggi_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugetelkyonggi_re',
        'bo_table' => 'hyugetelkyonggi_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      19 => 
      array (
        'text' => '휴게텔-인천/부천',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=hyugetelinchon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugetelinchon_re',
        'bo_table' => 'hyugetelinchon_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      20 => 
      array (
        'text' => '휴게텔 강원/충청/대전',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=hyugeteldaejeon_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugeteldaejeon_re',
        'bo_table' => 'hyugeteldaejeon_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      21 => 
      array (
        'text' => '휴게텔 경상/전라/제주',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=hyugeteljeju_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hyugeteljeju_re',
        'bo_table' => 'hyugeteljeju_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      22 => 
      array (
        'text' => '키스방-전국영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=kissall_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-kissall_re',
        'bo_table' => 'kissall_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      23 => 
      array (
        'text' => '립카페-전국영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=lipcafeall_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-lipcafeall_re',
        'bo_table' => 'lipcafeall_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      24 => 
      array (
        'text' => '핸플/패티쉬영토',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=show_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-show_re',
        'bo_table' => 'show_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      25 => 
      array (
        'text' => '선불폰/프로필 여행사/기타',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=trip_re',
        'icon' => 'fa-commenting-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-trip_re',
        'bo_table' => 'trip_re',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
    ),
  ),
  2 => 
  array (
    'text' => '커뮤니티',
    'href' => '#',
    'icon' => 'fa-comments',
    'target' => '_self',
    'line' => '공지사항',
    'sp' => '1',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '출석체크',
        'href' => 'http://192.168.1.17/gnuboard/plugin/attendance/m_attendance.php',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '공지사항',
        'sp' => '1',
        'limit' => '',
        'grade' => 0,
        'id' => 'plugin-attendance-page-attendance',
      ),
      1 => 
      array (
        'text' => '공지사항',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=notice',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-notice',
        'bo_table' => 'notice',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      2 => 
      array (
        'text' => '가입 인사',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=greeting',
        'icon' => 'fa-comments',
        'target' => '_top',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-greeting',
        'bo_table' => 'greeting',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      3 => 
      array (
        'text' => '자유 게시판',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=free',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-free',
        'bo_table' => 'free',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      4 => 
      array (
        'text' => ' 미수다(女)',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=woman',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-woman',
        'bo_table' => 'woman',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      5 => 
      array (
        'text' => ' 이벤트',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=event',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-event',
        'bo_table' => 'event',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      6 => 
      array (
        'text' => '쿠폰구매',
        'href' => '#',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      7 => 
      array (
        'text' => '가문게시판',
        'href' => '#',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      8 => 
      array (
        'text' => '왕궁 게시판',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=palace',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-palace',
        'bo_table' => 'palace',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      9 => 
      array (
        'text' => '아이템샵',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=shop',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-shop',
        'bo_table' => 'shop',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      10 => 
      array (
        'text' => '건의사항',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=suggestions',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-suggestions',
        'bo_table' => 'suggestions',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      11 => 
      array (
        'text' => '트위터 인증',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=twitter',
        'icon' => 'fa-comments',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-twitter',
        'bo_table' => 'twitter',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
    ),
  ),
  3 => 
  array (
    'text' => '고객센터',
    'href' => '#',
    'icon' => 'fa-headphones',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '1:1문의',
        'href' => 'http://192.168.1.17/gnuboard/bbs/qalist.php',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-qa',
      ),
      1 => 
      array (
        'text' => '파운드페니로전환',
        'href' => 'http://192.168.1.17/gnuboard/bbs/point.php',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-page-point',
      ),
      2 => 
      array (
        'text' => '파편조각페니로전환',
        'href' => 'http://192.168.1.17/gnuboard/bbs/point2.php',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-page-point2',
      ),
      3 => 
      array (
        'text' => '페니구매',
        'href' => '#',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      4 => 
      array (
        'text' => '환전',
        'href' => '#',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      5 => 
      array (
        'text' => '장터게시판',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=market',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-market',
        'bo_table' => 'market',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      6 => 
      array (
        'text' => '구인구직 게시판',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=job',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-job',
        'bo_table' => 'job',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      7 => 
      array (
        'text' => '실장업무게시판',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=work_board',
        'icon' => 'fa-headphones',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-work_board',
        'bo_table' => 'work_board',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
    ),
  ),
  4 => 
  array (
    'text' => '명예의전당',
    'href' => '#',
    'icon' => 'fa-trophy',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '계급 랭킹',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=levelrank',
        'icon' => 'fa-trophy',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-levelrank',
        'bo_table' => 'levelrank',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      1 => 
      array (
        'text' => '파운드 랭킹',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=pointrank',
        'icon' => 'fa-trophy',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-pointrank',
        'bo_table' => 'pointrank',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      2 => 
      array (
        'text' => '페니 랭킹',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=penyrank',
        'icon' => 'fa-trophy',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-penyrank',
        'bo_table' => 'penyrank',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      3 => 
      array (
        'text' => '가문 랭킹',
        'href' => '#',
        'icon' => 'fa-trophy',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  5 => 
  array (
    'text' => '파운드 게임',
    'href' => '#',
    'icon' => 'fa-globe',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
  ),
  6 => 
  array (
    'text' => ' 페니 게임',
    'href' => '#',
    'icon' => 'fa-bullseye',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '포카',
        'href' => '#',
        'icon' => 'fa-bullseye',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      1 => 
      array (
        'text' => '바둑이',
        'href' => '#',
        'icon' => 'fa-bullseye',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      2 => 
      array (
        'text' => '맞고',
        'href' => '#',
        'icon' => 'fa-bullseye',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  7 => 
  array (
    'text' => ' 자료실',
    'href' => '#',
    'icon' => 'fa-play-circle',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '  영화 ',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=movie',
        'icon' => 'fa-play-circle',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-movie',
        'bo_table' => 'movie',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      1 => 
      array (
        'text' => 'TV영상',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=tv',
        'icon' => 'fa-play-circle',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-tv',
        'bo_table' => 'tv',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      2 => 
      array (
        'text' => ' 웹툰/야설 ',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=ucc',
        'icon' => 'fa-play-circle',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-ucc',
        'bo_table' => 'ucc',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      3 => 
      array (
        'text' => '유튜브 영상',
        'href' => 'http://192.168.1.17/gnuboard/bbs/board.php?bo_table=request',
        'icon' => 'fa-play-circle',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-request',
        'bo_table' => 'request',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
    ),
  ),
);
?>